name: Build post

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  execute:
    runs-on: ubuntu-latest
    concurrency: post-${{ github.ref }}
    steps:
      - name: Get county data
        shell: bash
        run: |
          wget https://www2.census.gov/geo/tiger/TIGER2021/COUNTY/tl_2021_us_county.zip
          unzip tl_2021_us_county.zip
      - uses: adrn-blog/execute-post@main
        with:
          python-version: "3.10"
